### ISSUE TITLE
TypeScript 4.7 and up can’t find types

### ISSUE THREAD

**Issue by drwpow** [axtgr/wildcard-match#12]
## Issue

TypeScript introduced a change [in 4.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html) where `"types"` is no longer respected in the root of `package.json` and instead must be moved into `"exports"` ([docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html)).

<img width="1084" alt="CleanShot 2023-08-31 at 21 33 03@2x" src="https://github.com/axtgr/wildcard-match/assets/1369770/eab2fced-89b9-476c-8876-383dc1683d15">

## Solution

Update the package.json exports to [the recommended configuration](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html)

**Comment by keroiber** [comment]
Hello @axtgr,
will you incorporate the fix? It is not possible to use wildcard-match with newer typescript versions atm
thank you!

**Comment by nibble-4bits** [comment]
I'm having the same issue, are there any plans to address this issue, by any chance, @axtgr?

**Comment by axtgr** [comment]
Sorry this took so long, should be fixed now.

**Comment by drwpow** [comment]
No need to apologize; thanks so much for the great library! 🙂
