### ISSUE TITLE
typescript LibCheck failed with 4.1.0

### ISSUE THREAD

**Issue by chenavazer** [axtgr/wildcard-match#2]
node_modules/wildcard-match/build/index.d.ts:9:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

"typescript": "^4.0.3"
"typescript": "^3.9.7"

No error with:
"compilerOptions": {
"skipLibCheck": true
}

**Comment by chenavazer** [comment]
no error with 4.0.0

**Comment by axtgr** [comment]
Thanks for the report, fixed in 4.1.1. And I thought I was being clever by merging the type declarations.
